package test

import (
	"fmt"

	"github.com/go-faker/faker/v4"
	"github.com/soffa-projects/foundation-go/h"
)

func FakeEmail() string {
	return faker.Email()
}

func FakeName() string {
	return faker.Name()
}

func FakePassword() string {
	return faker.Password()
}

func FakeUrl() string {
	return faker.URL()
}

func FakePhone() string {
	return faker.Phonenumber()
}

func FakeEmailProvider() string {
	return "faker://sender"
}

func FakeSecretProvider() string {
	return "faker://secrets"
}

func InMemoryCacheProvider() string {
	return "memory"
}

func TestDatabaseURL() string {
	return fmt.Sprintf("file:%s?mode=memory&cache=shared", h.RandomString(5))
}

func FakePubSubProvider() string {
	return "faker://pubsub"
}

//DatabaseURL: fmt.Sprintf("sqlite://file:%s?_fk=1", dbFile),
//DatabaseURL:         fmt.Sprintf("postgres://postgres:postgres@localhost:5432/soffa-sso-test?schema=%s&sslmode=disable", schema),

func JWKSBase64() (string, string) {

	publicBase64 := "ewogICJrdHkiOiAiUlNBIiwKICAiZSI6ICJBUUFCIiwKICAidXNlIjogInNpZyIsCiAgImtpZCI6ICJ3MUJBd2l6UmxDMHo1WnA0NG05eEtQalcwbi1hWU9VY0VXV3hwS205YUdZIiwKICAiYWxnIjogIlJTMjU2IiwKICAibiI6ICJqR3dkX1JLQzNBZHgtU1NtVGZ0Sm9ic1dsWTRkMHZKbU9Edjdwa1phRFMxZzNMdjllMUZZLWZNel84cXZsV09mMUdaY0tjSDVBRTE3R3gwWkVLMHVmN1NXVUVIQVVVR1JtY2pTak5FR1hISzNucmMtdnh3UkU5bWZlOGtHeHBtTDkyQkZFejRmemxmQmUwQnVwZzJwalc3VnRtdUVmSVV5VlFIdElPVHhVeUV3NzFZamdzWXRfc0pKTHU1cElucVJqMVNKMDAxdDBHQkRLbnM0SFdQVThuZVJjRl9pcDNPMVo0S1ZZMXNONmRXSnJkU0lMX2FBVU00ekU3XzNxVjdpS2VvdFBnTzlhMzR5RlVrbVJnZ3dMWFpmbFNILWM1SG1LYjZmcWFNR1N2QUdnMXBZOWd1QThNbzU3NzRhbkxrVF9wdnBrN0ZUY3RuRGttY0NXX21aSHciCn0="

	privateBase64 := "ewogICJwIjogInZ6bmsxRkpOQ2lxZmdZWGRQYW5lb0xxSEcxazhSeUhOckJvd2hVVHFXdlp2OFFWRUZ6OXpqUEUzS0R4R1RFOXpwVUhhVWFoLUlTV0lRVlBxdDJUOWVjNEVTcmNnRkg1N09FRmhmVHJJaF9CX1R0dkkwWnpNZlNnb1RvMXhyZzJod3NZSFRib2hEWENpRzl6SThQN09wcnphVm1ZMFVkam1HTzRnaFRibTdRTSIsCiAgImt0eSI6ICJSU0EiLAogICJxIjogInVfeko4VlNpbFZTUDE3SHJtejNBbGdPSmRTZ2tfOWxQdHAyUU5HbnZRWnkyc0k1V0ZHWklaeTByS2pYWkN6WjJGOTdMUEpTTXlMT1lTYnd0ME9yeW5qcUM1VmNWVzI4LXo5emJDWGVfb0s1MlJQLWZoMUdyal9QUzU3VHRiaDBsNVlfRjhHVjlGaWxqdDZBTDVST0ZzVW11MUI0clo4QmwwX1JnUVNlZUFyVSIsCiAgImQiOiAiQklrMWlzZ19TLVk5cTBPZ3o2SVBaZGNLU3JoMWhDdnFXMlNzbzFsZ2JVNks4M1pySU1HbTh5UUZDUDAtSU1CQUdIZGFBTXRRUk04NzY4dEwxUHNUSm5McDdCdkRuNXhUbkxrY19BbUFnQm9Bam5MeTV1OThLYno4NXQyLWgwbk1lS2cyY3dHdHUxZWdXMV9nY3lLNzJHSzlLcEJjamowclBBMjg0RFFsQzM5WnVtWkZwT1ZRWXhTWEJjX0QwZkxtQXg2RF9qNTNucW56WUNGZ0ZpZ0czQ1ZjS2pDRTBkeGl0UDhDeXBJWU9UQVR3bmZEQVRMVkFIYXVsN2VmNUM2c190a1l2cU9XWXpxajlHUUdfNWZDSnJ0SVdXNkN4MExuZlFkVDcwOEZVQmFkdkREenJmdUlhVlljelJkMTdGYUdyLVBESWphTGxyaDdOLUZqRExQcENRIiwKICAiZSI6ICJBUUFCIiwKICAidXNlIjogInNpZyIsCiAgImtpZCI6ICJ3MUJBd2l6UmxDMHo1WnA0NG05eEtQalcwbi1hWU9VY0VXV3hwS205YUdZIiwKICAicWkiOiAiSjY3cWhTZ3lHVzRSQnNRSF9kVEQ2aU54X0pVc3Vqd25MellFZFRzRE81dUFmb0d5X2FEcDZRN3hkcC1JbGVfanpHU0k0bGlHOUE1RWRLUGlEWGJkV2tPYzJWOTlQYjJUcEhkS25Ca2N4Y0VablBqMlg2UVMzSjdNTXFWeTB0bzNzVG9vSVVDWFA2VF8xRy03M21fcU10ZF9qZk1KbURqOEFSQ21BdmxjMDlvIiwKICAiZHAiOiAiVHJuaC1IdU5sZ0xvT2lYSGFNeVhpQ3BpMXlLTXkyZ2lTWmxhb25NMTNJOGFsT3FyRnJzYnNrbllnR3NZTWZCXzF1aGVua0cwODZhRkN3Z21XS3h1SW9ocmdlc1VmUHQ1ZFRhTmtVWHpLdXdiTFhjVW5SOWxuSjA4d3VJLWlfNjJ1djVXSVd6Z2tLenZRSE5NRXRPRWRtYkhxTXhZLTkxRkZieHJqUXlHVThzIiwKICAiYWxnIjogIlJTMjU2IiwKICAiZHEiOiAiVVg5YUhTSFFDbVZLcHZ3ZlpJSDFDQlFvZDM0YjdEOU42NkdMYnUydUtBZkV1LTQ1SzBiY2hMNTBSQ3hzR0F4WVRpanNleXI3amRjdVlta09nOUFYdHJrdkhqWU9zRUVlUGdkRmZtbEh6bVZVS0wyWmI1VGNoOV93d3pzUTRfZ0hBZXEtcVdXV1FSRlloYmNBOFNMeGh0YW0wSmJ6d2xzS3lrVGJwZU9EQVRFIiwKICAibiI6ICJqR3dkX1JLQzNBZHgtU1NtVGZ0Sm9ic1dsWTRkMHZKbU9Edjdwa1phRFMxZzNMdjllMUZZLWZNel84cXZsV09mMUdaY0tjSDVBRTE3R3gwWkVLMHVmN1NXVUVIQVVVR1JtY2pTak5FR1hISzNucmMtdnh3UkU5bWZlOGtHeHBtTDkyQkZFejRmemxmQmUwQnVwZzJwalc3VnRtdUVmSVV5VlFIdElPVHhVeUV3NzFZamdzWXRfc0pKTHU1cElucVJqMVNKMDAxdDBHQkRLbnM0SFdQVThuZVJjRl9pcDNPMVo0S1ZZMXNONmRXSnJkU0lMX2FBVU00ekU3XzNxVjdpS2VvdFBnTzlhMzR5RlVrbVJnZ3dMWFpmbFNILWM1SG1LYjZmcWFNR1N2QUdnMXBZOWd1QThNbzU3NzRhbkxrVF9wdnBrN0ZUY3RuRGttY0NXX21aSHciCn0="

	return publicBase64, privateBase64

}
