version: "3"

tasks:
  tidy: # task tidy
    cmds:
      - go mod tidy
  install:
    cmds:
      - curl -sSfL https://goblin.run/github.com/air-verse/air | sh #(live reload)
  upgrade:
    cmds:
      - go get -u ./...
      - go mod tidy
  test:
    cmds:
      - GO_ENV=test go test -v ./..